### ISSUE TITLE
Additional VAT number validation

### ISSUE THREAD

**Issue by ivan-milovanovic-troxo** [atomia/AtomiaStore#5]
Hi,

We need VAT validation using service http://ec.europa.eu/taxation_customs/vies/technicalInformation.html in contact form. Mladen told us that Billing API function ValidateVatNumber already validates VAT using that service. Is this validation maybe already implemented in AtomiaStore?

I checked AtomiStore source code for ContactModel and there is some validation using CustomerValidation attribute in Atomia.Store.AspNetMvc.Models.CompanyExtraInfo class for VatNumber variable but CustomerValidation attribute does not seem to validate VAT number using Billing API (function ValidateVatNumber). I tested VAT number validation using invalid VAT number SE556682387705 for country Sweden but form validation passed and order was later processed without any error.

Also what is the best way of adding new data validation attribute to VatNumber filed? There is internal variable Parent in ContactSubmodel which seems to complicate things..

**Comment by kdpersson** [comment]
It's been on the backlog for a while. I'm working to get it done this week so it will be included in the 15.9 release.

**Comment by kdpersson** [comment]
Should now be fixed by 6bb87de41b722b99b17eedbc0905e231a94f3c65

In the account info page it still does a simple check with regex to no hold up the process with an inline call to the external service.

The check with VIES service is done in the background in the checkout page, and is transparent to the user unless the VAT number is invalid or the service is down, in which case the user can try to revalidate, or go through with the order anyway with VAT applied.
